# Generated by Django 2.2 on 2021-04-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='user',
            new_name='user_id',
        ),
    ]
